FROM python:3.11-slim

WORKDIR /app

# Устанавливаем зависимости
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    postgresql-client \
    ca-certificates \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://download.docker.com/linux/static/stable/x86_64/docker-26.1.3.tgz \
    | tar xz --strip 1 -C /usr/local/bin docker/docker

COPY requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

# Копируем скрипты
COPY wg-collector.py /app/wg-collector.py

CMD ["python", "wg-collector.py"]
